//go:build set3lab

// Copyright 2024 TomTonic
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package setcompare

import (
	"math/bits"
	"reflect"

	"github.com/TomTonic/Set3/hashing"
)

// The four key types the suite runs. They are not four flavours of the same
// thing: each one takes a different route through the hashing package, and the
// route is most of what separates Set3 from the native map on small keys.
//
//   - uint64      a dedicated 64-bit routine, one multiply-xor round
//   - string      the length-dispatched wyhash string path
//   - struct3x64  three uint64 fields, hashed as one raw byte block
//   - structmixed a uint64 and a string, which no raw-block hasher can take,
//     so it falls back to Go's hash/maphash
//
// The last one exists to keep the comparison honest: it is the case where Set3
// gives up its specialised hashing and has to win on table layout alone.
const (
	keyTypeUint64 = "uint64"
	keyTypeString = "string"
	keyTypeStruct = "struct3x64"
	keyTypeMixed  = "structmixed"
)

// tenantKey is three 64-bit identifiers, the shape of a composite key in a
// multi-tenant store. Every field is a fixed-size integer, so the hashing
// package hashes the struct as one 24-byte block without touching its fields.
type tenantKey struct {
	Tenant uint64
	Object uint64
	Shard  uint64
}

// eventKey pairs an identifier with a short label, the shape a struct key
// usually has in practice. The string field makes the value non-contiguous,
// so raw-block hashing is not available and Set3 uses hash/maphash for it.
type eventKey struct {
	ID     uint64
	Region string
}

// regions is a small fixed vocabulary, so that eventKey values differ in their
// identifier rather than in their label — which is what real event keys do.
var regions = [8]string{"eu-central", "eu-west", "us-east", "us-west", "ap-south", "ap-north", "sa-east", "af-south"}

// knownKeyType reports whether name is one of the key types this suite knows,
// so that a typo in SET3_CMP_KEYS fails at startup instead of silently
// producing an empty run.
func knownKeyType(name string) bool {
	switch name {
	case keyTypeUint64, keyTypeString, keyTypeStruct, keyTypeMixed:
		return true
	}
	return false
}

// mix is splitmix64's finalizer. It is a bijection on uint64, which is the
// only property the suite needs from it: distinct inputs are guaranteed to
// produce distinct keys, so key sets can be generated by counting rather than
// by generating random values and rejecting collisions through a helper map.
// That matters at eight million keys, where the rejection loop would cost more
// than the measurement.
func mix(z uint64) uint64 {
	z += 0x9e3779b97f4a7c15
	z = (z ^ (z >> 30)) * 0xbf58476d1ce4e5b9
	z = (z ^ (z >> 27)) * 0x94d049bb133111eb
	return z ^ (z >> 31)
}

// memberDomain and missDomain are disjoint id ranges. Because mix is a
// bijection, keys built from disjoint id ranges are themselves disjoint, which
// is what makes a generated "miss" reliably a miss.
const (
	memberDomain uint64 = 0
	missDomain   uint64 = 1 << 42
	secondDomain uint64 = 1 << 43 // the second operand of the set-algebra workload
)

// hex16 renders v as exactly 16 lowercase hex digits into dst.
// It exists because the string key generator runs up to eight million times
// per cell and fmt.Sprintf would dominate the setup time.
func hex16(dst []byte, v uint64) {
	const digits = "0123456789abcdef"
	for i := 15; i >= 0; i-- {
		dst[i] = digits[v&0xf]
		v >>= 4
	}
}

// keyMaker turns an id into a key of type T. Distinct ids must produce
// distinct keys; every implementation here gets that from mix.
type keyMaker[T comparable] func(id uint64) T

// makeUint64Key produces a uint64 key. The identity of the id is destroyed by
// mix so that consecutive ids do not land in consecutive buckets, which would
// flatter both implementations equally but describe no real workload.
func makeUint64Key(id uint64) uint64 { return mix(id) }

// makeStringKey produces a 20-byte identifier of the shape a real system uses
// for opaque ids: a short prefix and a fixed-width hex body.
func makeStringKey(id uint64) string {
	buf := make([]byte, 20)
	copy(buf, "usr-")
	hex16(buf[4:], mix(id))
	return string(buf)
}

// makeTenantKey spreads one id over three fields, so that all 24 bytes of the
// key carry entropy and the raw-block hasher has real work to do.
func makeTenantKey(id uint64) tenantKey {
	a := mix(id)
	return tenantKey{Tenant: a >> 40, Object: a, Shard: bits.RotateLeft64(a, 21) & 0xffff}
}

// makeEventKey varies the identifier and picks the label from a small
// vocabulary, which is what makes this key type non-eligible for raw-block
// hashing without making it artificial.
func makeEventKey(id uint64) eventKey {
	a := mix(id)
	return eventKey{ID: a, Region: regions[a&7]}
}

// rawBlockEligible reports whether the hashing package will hash T as one raw
// byte block. The suite records this per key type in the CSV, because "Set3
// lost on this key type" reads very differently once you know it was hashing
// through maphash at the time.
func rawBlockEligible[T comparable]() bool {
	var zero T
	return hashing.CanUseUnsafeRawByteBlockHasherType(reflect.TypeOf(zero)).Eligible
}

// buildKeys materialises count keys from consecutive ids starting at base.
//
// The keys are distinct by construction (see mix), and the slice is filled in
// id order, which means the *values* are in random order — a set built from it
// sees the same lack of locality a real fill sees.
func buildKeys[T comparable](make_ keyMaker[T], base uint64, count int) []T {
	out := make([]T, count)
	for i := range out {
		out[i] = make_(base + uint64(i)) //nolint:gosec
	}
	return out
}

// mixedQueries builds a query stream of length streamLen in which hitRatio of
// the entries are members of the given key slice and the rest are not.
//
// The stream is shuffled rather than laid out in blocks, so the branch
// predictor cannot learn the hit pattern; a blocked stream would make both
// implementations look better than they are, and by different amounts.
// streamLen is rounded up to a power of two so the batch loop can index it
// with a mask instead of a division.
func mixedQueries[T comparable](members, misses []T, hitRatio float64, streamLen int) []T {
	n := 1
	for n < streamLen {
		n <<= 1
	}
	out := make([]T, n)
	var rng = newSplitmix(0x5eed_5ca1_ab1e_0001)
	for i := range out {
		if rng.float64() < hitRatio {
			out[i] = members[rng.uint32n(uint32(len(members)))] //nolint:gosec
		} else {
			out[i] = misses[rng.uint32n(uint32(len(misses)))] //nolint:gosec
		}
	}
	return out
}

// zipfStream builds a stream of length streamLen drawn from members with a
// heavy head: a few keys appear very often, most appear once or twice.
//
// This is what a deduplication workload actually sees. A uniform stream would
// make every lookup a cache miss and would overstate the cost of both
// implementations; the skew is where the interesting behaviour is, because the
// hot keys stay resident and the comparison comes down to the probe sequence
// rather than to memory latency.
func zipfStream[T comparable](members []T, streamLen int) []T {
	out := make([]T, streamLen)
	rng := newSplitmix(0x5eed_5ca1_ab1e_0002)
	n := uint64(len(members))
	for i := range out {
		// A ratio of two uniforms gives a 1/x-ish tail cheaply and without a
		// table: about 30% of draws land in the first 1% of the key space.
		u := rng.float64()
		idx := uint64(float64(n) * u * u * u)
		if idx >= n {
			idx = n - 1
		}
		out[i] = members[idx]
	}
	return out
}

// splitmix is a tiny deterministic generator used only for building test data.
// It is not the DPRNG from rtcompare because nothing here needs that generator's
// guarantees, and inlining a three-line step keeps eight-million-element setup
// out of the profile.
type splitmix struct{ state uint64 }

func newSplitmix(seed uint64) *splitmix { return &splitmix{state: seed} }

func (s *splitmix) next() uint64 {
	s.state += 0x9e3779b97f4a7c15
	return mix(s.state - 0x9e3779b97f4a7c15)
}

func (s *splitmix) float64() float64 { return float64(s.next()>>11) / (1 << 53) }

// uint32n returns a value in [0,n) without a division, via Lemire's
// multiply-shift reduction. The slight bias for non-power-of-two n does not
// matter for choosing which key to look up next.
func (s *splitmix) uint32n(n uint32) uint32 {
	return uint32((uint64(uint32(s.next())) * uint64(n)) >> 32) //nolint:gosec
}
