name: Test Coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.1'

      - name: Run tests and generate coverage report
        run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...

      - name: Generate coverage badge
        uses: vladopajic/go-test-coverage@v2
        with:
          profile: cover.out
          local-prefix: github.com/TomTonic/Set3
          threshold-total: 95
          git-branch: badges 
